-- Phase 3: Add image analysis columns (PostgreSQL)
ALTER TABLE files ADD COLUMN IF NOT EXISTS blur_score DOUBLE PRECISION;
ALTER TABLE files ADD COLUMN IF NOT EXISTS brightness_score DOUBLE PRECISION;
ALTER TABLE files ADD COLUMN IF NOT EXISTS colorfulness_score DOUBLE PRECISION;
ALTER TABLE files ADD COLUMN IF NOT EXISTS is_blurry BOOLEAN;
